on: push
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.0
      - run: ls
      - run: flutter pub get
      - run: flutter build apk
      - run: echo "::set-env name=NOW::$(date +'%Y-%m-%dT%H:%M:%S')"
      
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ env.NOW }}

      
