on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.0
      - run: ls
      - run: flutter pub get
      - run: flutter build apk
      
      
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: a
          release_name: Release ${{ github.ref }}
          body: |
            Automated release from Github actions
          draft: false
          prerelease: false
